---
title: "Random Control Trail - Some theorical glance"
author: "Huihang Liu"
date: "5/15/2021"
output: bookdown::html_document2
bibliography: Ref-RCT.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

We consider the problem of ATE estiamtion with data from random control trials (RCT). 

We mainly follow @schochet2010regression and @bloniarz2016lasso to develop our methods and theories. 
We consider the problem of ATE estiamtion with data from random control trials (RCT). 
They illustrated that the estiamtion precision could be improved by introducing covariates. 

# Theorical Target

Let $T$ be the indicator of status on treatment or control condition, $T=1$ means the treated, and $T=0$ means controled. 
Let $Y_i$ be the outcome of the $i$th individual, let $Y_{T,i}$ and $Y_{C,i}$ be the potential outcome in the treated 
We consider the following non-parameter model,  
$$
\begin{align}
Y_i = T_i Y_{T=1,i} + (1-T_i) Y_{T=0,i}
(\#eq:nonparamodel)
\end{align}
$$
where $i=1,\dots,n$ and $n$ subjects are randomly assigned to a treatment or control condition. 

# References
